spring:
  application:
    name: weather-app-be

  datasource:
    url: jdbc:h2:mem:weather-app;
    username: sa
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    import: optional:file:.env[.properties]

weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${API_KEY:default}
